#!/bin/sh

function focus () {
  [ -z "$SVIM_FOCUS_COMMAND" ] || $SVIM_FOCUS_COMMAND $1
}

wids=(`xdotool search --class --onlyvisible Gvim`)

nw=${#wids[*]}

if [ $nw -lt 1 ]
then
  gvim "$@"
  exit
elif [ $nw = 1 ]
then
  wid=${wids[0]}
  name=`xprop WM_NAME -id $wid | sed 's/.*\-\s\|"$//g'`
elif true
then
  if [ -n "$SVIM_SELECTOR" ]
  then
    selector="$SVIM_SELECTOR"
  elif which percol &> /dev/null
  then
    selector='percol'
  elif which zenity &> /dev/null
  then
    selector='zenity --list --column Vim'
  else
    head -1
  fi

  select=`echo ${wids[*]} | xargs -d " " -n 1 xprop WM_NAME -id | sed 's/^.* = "\|"$//g' | nl -n ln | $selector`

  wid=${wids[`echo $select | sed 's/\s.*//'`-1]}
  name=`echo $select | sed 's/.*- \|"$//g'`
fi

case `basename "$0"` in
  $SVIM_COMMAND_NORMAL | svim)
    gvim --servername $name --remote "$@"
    focus $wid
  ;;
  $SVIM_COMMAND_TAB | stvim)
    gvim --servername $name --remote-tab "$@"
    focus $wid
  ;;
esac

